Pin @react-navigation/* packages to yarn.lock versions
This resolves errors during `npm install`'s `prepare` phase. Because of the lack of a `package-lock.json`
file, npm installed the latest versions of all the `@react-navigation/*`
packages and their type definitions were not matching.

The errors were:
```
ℹ Generating type definitions with tsc
src/native-stack/navigators/createNativeStackNavigator.tsx:32:5 - error TS2314: Generic type 'StackNavigationState' requires 1 type argument(s).
32     StackNavigationState,
       ~~~~~~~~~~~~~~~~~~~~
src/native-stack/navigators/createNativeStackNavigator.tsx:32:5 - error TS2558: Expected 5 type arguments, but got 4.
32     StackNavigationState,
       ~~~~~~~~~~~~~~~~~~~~~
33     StackRouterOptions,
   ~~~~~~~~~~~~~~~~~~~~~~~
34     NativeStackNavigationOptions,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
35     NativeStackNavigationEventMap
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/native-stack/navigators/createNativeStackNavigator.tsx:73:7 - error TS2322: Type 'Record<string, Descriptor<Record<string, object | undefined>, string, any, NativeStackNavigationEventMap, {}>>' is not assignable to type 'NativeStackDescriptorMap'.
  Index signatures are incompatible.
    Type 'Descriptor<Record<string, object | undefined>, string, any, NativeStackNavigationEventMap, {}>' is not assignable to type 'Descriptor<Record<string, object | undefined>, string, any, NativeStackNavigationOptions, {}>'.
      Types of property 'options' are incompatible.
        Type 'NativeStackNavigationEventMap' has no properties in common with type 'NativeStackNavigationOptions'.
73       descriptors={descriptors}
         ~~~~~~~~~~~
  src/native-stack/views/NativeStackView.tsx:24:3
    24   descriptors: NativeStackDescriptorMap;
         ~~~~~~~~~~~
    The expected type comes from property 'descriptors' which is declared here on type 'IntrinsicAttributes & Props'
src/native-stack/navigators/createNativeStackNavigator.tsx:79:3 - error TS2314: Generic type 'StackNavigationState' requires 1 type argument(s).
79   StackNavigationState,
     ~~~~~~~~~~~~~~~~~~~~
src/native-stack/types.tsx:31:3 - error TS2314: Generic type 'StackNavigationState' requires 1 type argument(s).
31   StackNavigationState,
     ~~~~~~~~~~~~~~~~~~~~
src/native-stack/types.tsx:254:3 - error TS2314: Generic type 'StackNavigationState' requires 1 type argument(s).
254   StackNavigationState,
      ~~~~~~~~~~~~~~~~~~~~
src/native-stack/views/NativeStackView.tsx:22:10 - error TS2314: Generic type 'StackNavigationState' requires 1 type argument(s).
22   state: StackNavigationState;
            ~~~~~~~~~~~~~~~~~~~~
src/native-stack/views/NativeStackView.tsx:36:26 - error TS7006: Parameter 'route' implicitly has an 'any' type.
36       {state.routes.map((route) => {
                            ~~~~~
Found 8 errors.
✖ Failed to build definition files.

```